version: "3.7"

services:
        src:
                container_name: v1.00
                image: v1.00:docker-compose
                build:
                        context: .
                ports:
                        - "3001:3001"
                environment:
                        - EXTERNAL_PORT=3001
                        - POSTGRES_DB=db_postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=12345
                        - POSTGRES_HOST=db
                depends_on:
                        - db
        db:
                container_name: db_postgres
                image: "postgres:12"
                ports:
                        - "5432:5432"
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=12345
                        - POSTGRES_DB=db_postgres
                volumes:
                        - nps_data:/var/lib/postgresql/data
                        - ./node_modules
volumes:
        nps_data: {}
