version: "2.2"

services:      
        db:
                image: "postgres:12"
                ports:
                        - "5432:5432"
                environment:
                        POSTGRES_USER: gabi
                        POSTGRES_PASSWORD: 12345
                        POSTGRES_DB: dbname
                volumes:
                        - db:/var/lib/postgresql/data
    
        src:
                container_name: v1.00
                image: v1.00:docker-compose
                build:
                        context: .
                depends_on:
                        - db
                ports:
                        - "3001:3001"
                environment:
                        DB_HOST: db
                        DB_PORT: 5432
                        DB_USER: gabi
                        DB_PASSWORD: 12345
                        DB_NAME: dbname
                links:
                        - db
                volumes:
                        - ".:/v1.00"
                        - "/v1.00/node_modules"
volumes:
        db: {} 
