version: "3.7"

services:
        src:
                container_name: v1.00
                image: v1.00:docker-compose
                build:
                        context: .
                ports:
                        - "3001:3001"
                environment:
                        - EXTERNAL_PORT=3001
